server:
  port: 8080  # 기본 포트

spring:
  config:
    activate:
      on-profile: default  # 기본 프로파일 활성화
---

spring:
  config:
    activate:
      on-profile: port8081  # 포트 8081 프로파일 활성화

server:
  port: 8081
