name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # 빌드 결과물 출력
      - name: Display JAR files
        run: |
          echo "Generated JAR files:"
          ls -l build/libs

      # plain 버전 제외하고 JAR 파일 전송
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy jar files excluding plain version
        env:
          SSH_PASSWORD: ${{ secrets.SSHPASSWORD }}
        run: |
          for jar in build/libs/*.jar; do
            if [[ ! "$jar" =~ -plain\.jar$ ]]; then
              sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -P 8080 "$jar" root@49.236.136.132:/home/jarFiles
            fi
          done

      # 쉘스크립트 파일 실행
      - name: Execute shell script on remote server
        env:
          SSH_PASSWORD: ${{ secrets.SSHPASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 8080 root@49.236.136.132 'bash /home/shellScript/github_action_shell.sh'

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
